### ISSUE TITLE
Single prediction support?

### ISSUE THREAD

**Issue by rbnx** [pablrod/p5-AI-XGBoost#4]
Is there a way or are there plans to add support to make predictions for a single observation.
or is using XGDMatrixCreateFromMat the only way to do it right now?

**Comment by pablrod** [comment]
Currently the recommended way to make a prediction for a single observation is:
```perl
...
my $single_observation_dmatrix = AI::XGBoost::DMatrix->From(matrix => [[...]], label => [ ]); # Label is optional depends on your data
$booster->predict(data => $single_observation_dmatrix);
```
So now there are two ways:
* Using `AI::XGBoost::CAPI` or `AI::XGBoost::CAPI::RAW`
* Using `AI::XGBoost::DMatrix`
But both involve the creation of a `DMatrix`. This is because `XGBoost` is `DMatrix` oriented.

I'm very open to add a shortcut to make this easier. I propose a method in `AI::XGBoost::Booster` object that can accept a row and optionally a label. 

What do you think? Do you have something in mind?

**Comment by rbnx** [comment]
That's great, I hadn't seen that part of the API so I was using `XGDMatrixCreateFromMat`
closing this issue for now if I come up with an intuitive shortcut I will create a pull request.
Thanks.
